### ISSUE TITLE
カスタムキーをなるべく使わない方法に書き直す

### ISSUE THREAD

**Issue by Rindrics** [Rindrics/keyball#2]
https://github.com/Rindrics/keyball/commit/f3afe902834452bf1bb41789e5cadfdb65682c03 の時点で実装方針がよくないことに気づいた
- そもそも全てのキーがメモリに載り切らない
    - HANDLE_NICOLA_KEY とか HANDLE_DVORAK_KEY などのカスタムキーを定義しているため
-  カスタムキーに頼るのではなく、KC_A などの普通のキー操作を丁寧に条件判定で処理していくほうがよさそう
    - 道理で、`process_record_user` 中の `return true` の出番がないと思った

**Comment by rindrics** [comment]
配列面に QWERTY 名でマップするのか、Dvorak でマップするのかは自分の認知次第

たぶん Dvorak になると思う

**Comment by rindrics** [comment]
でも NICOLA のシフト動作は COMBO でカスタムキー使ったほうがよさそう。同時押し判定が buggy になってしまう

**Comment by rindrics** [comment]
いろいろあったが親指シフトキーをカスタムキーじゃなく LGUI みたいな普通のキーにするのもコツだった

**Comment by rindrics** [comment]
closed by #3
